# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0c5d5a5764c9606b4fd4d9f0f48d1d06a4041ad6cc1c1d085d1db0248e2ba198526b3def98fd02c55bf96120742aa408f9d8fcccacbee9f92399b6dde3065ddf

test:
  secret_key_base: fdfcfe7fbdd65a7856d299bcae555e7b968dedfe8431c907b451a50dbb150748bbcd03b4715a24169145c8b57b9c8617dbb979f17ea2abdf30ec0e2e7a02d5bc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
